# ansible-playbook playbook.yml
---
- name: Docker swarm update serial example
  hosts: localhost
  vars:
    swarm_managers: "{{ groups['swarm_managers'] }}" 
    swarm_manager_parallel_update: 1 # number of managers to update at the same time
    swarm_worker_parallel_update: 2  # number of workers to update at the same time

    # 1. Iterate `docker_managers`
    # 2. Replace hostname with `docker_manager_parallel_update` cast to a string
    # 3. Cast all in list to integers
    # 4. Add `docker_worker_parallel_update` to the end of the list generated at 3
    #    ensuring it is also an integer

    swarm_upgrade_serial: "{{
      groups['swarm_managers']
      | map('regex_replace', '^.*$', swarm_manager_parallel_update | string )
      | map('int') | list
      + [ swarm_worker_parallel_update | int ]
    }}"

  tasks:
    - name: Print swarm_managers
      debug: var=swarm_managers

    - name: Print swarm_upgrade_serial
      debug: var=swarm_upgrade_serial

