version: '3.9'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      PGPASSFILE: /secrets/pgpass
      POSTGRES_HOST_AUTH_METHOD: password

    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    tmpfs: /secrets
