# ansible-playbook create-serial-list.yml
---
- name: Docker update serial example
  hosts: localhost
  vars:
    docker_managers: ["M1", "M2", "3"]
    docker_manager_parallel_update: 1 # number of managers to update at the same time
    docker_worker_parallel_update: 2  # number of workers to update at the same time

    # 1. Iterate `docker_managers`
    # 2. Replace hostname with `docker_manager_parallel_update` cast to a string
    # 3. Cast all in list to integers
    # 4. Add `docker_worker_parallel_update` to the end of the list generated at 3
    #    ensuring it is also an integer

    docker_upgrade_serial: "{{
      docker_managers
      | map('regex_replace', '^.*$', docker_manager_parallel_update | string )
      | map('int')
      + [ docker_worker_parallel_update | int ]
    }}"

  tasks:
    - name: Print docker_managers
      debug: var=docker_managers    

    - name: Print docker_upgrade_serial
      debug: var=docker_upgrade_serial

