# ansible-playbook test.yml
---
- name: Docker update serial example
  hosts: localhost
  vars:
    docker_managers: ["M1", "M2", "M3"]
    docker_manager_parallel_update: 1 # number of managers to update at the same time
    docker_worker_parallel_update: 2  # number of workers to update at the same time
    docker_upgrade_serial: "{{ docker_managers | map('int', docker_manager_parallel_update) + [ docker_worker_parallel_update ] }}"
  
  tasks:
    - name: Print docker_managers
      debug: var=docker_managers
    
    - name: Print docker_upgrade_serial
      debug: var=docker_upgrade_serial
